# Generated by Django 3.1.7 on 2021-03-01 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
    ]
